### ISSUE TITLE
Hi, can RPC-module be detached ?

### ISSUE THREAD

**Issue by utmostkindy** [DragonKingpin/Hydra#6]
The RPC module seems to be original designed and integrated into the main system. Is it possible to be detached?

**Comment by DragonKingpin** [comment]
Thanks for following Hydra~

`WolfUMC` is not only a original RPC, but a common message middle layer framework based on Netty. Yes, it has be integrated into Hydra, the primary purpose of `WolfUMC` is a common high performance information exchange component, which is using to implement other functional module (The RPC-Imp is one of its archetype).

Unfortunately, Yet, the detach-scheme is not on agenda, due to the massive dependences problem. It may be detached late.
